\documentclass[b5paper]{article}
\usepackage{pdflscape}
\usepackage{color}
\usepackage[dvipsnames]{xcolor}
\begin{document}
\SweaveOpts{concordance=TRUE}
\begin{table}[ht]
\begin{tabular}{rrrrrrr}
  \hline
 & Leadership..Effectiveness  \\ 
  \hline
Leadership..Effectiveness & 1.00 \\ 
  {\color{PineGreen} Extraversion} & {\color{PineGreen} 0.39} \\ 
  Neuroticism & -0.49 \\ 
 {\color{PineGreen} Conscientiousness } & {\color{PineGreen} 0.70}  \\ 
  Aggreeableness & -0.10 \\ 
  Openenss & 0.20 \\ 
   \hline
\end{tabular}
\end{table}
% latex table generated in R 3.3.0 by xtable 1.8-2 package
% Sat May 14 16:10:34 2016
\begin{table}[ht]
\begin{tabular}{rrrrr}
  \hline
 & Estimate & Std. Error & t value & Pr($>$$|$t$|$) \\ 
  \hline
(Intercept) & -2.6946 & 0.7645 & -3.52 & 0.0007 \\ 
  Extraversion & 0.2195 & 0.0147 & 14.97 & 0.0000 \\ 
  Neuroticism & -0.3255 & 0.0174 & -18.76 & 0.0000 \\ 
  Conscientiousness & 0.3481 & 0.0129 & 27.03 & 0.0000 \\ 
  Aggreeableness & -0.0445 & 0.0117 & -3.81 & 0.0002 \\ 
  Openenss & 0.1122 & 0.0146 & 7.70 & 0.0000 \\ 
   \hline
\end{tabular}
\end{table}
\begin{table}[ht]
\begin{tabular}{lrrrrr}
  \hline
 & Df & Sum Sq & Mean Sq & F value & Pr($>$F) \\ 
  \hline
Extraversion & 1 & 305.30 & 305.30 & 226.44 & 0.0000 \\ 
  Neuroticism & 1 & 462.74 & 462.74 & 343.22 & 0.0000 \\ 
  Conscientiousness & 1 & 988.26 & 988.26 & 733.00 & 0.0000 \\ 
  Aggreeableness & 1 & 19.95 & 19.95 & 14.80 & 0.0002 \\ 
  Openenss & 1 & 79.92 & 79.92 & 59.28 & 0.0000 \\ 
  Residuals & 94 & 126.73 & 1.35 &  &  \\ 
   \hline
\end{tabular}
\end{table}
\end{document}